on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "slides/**"

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install dependencies
        run: |
          install.packages(c("countdown", "rmarkdown", "knitr", "ggplot2",
          "dplyr", "tidyr", "tibble", "kableExtra", "RColorBrewer", "datasauRus",
          "medicaldata", "remotes", "tsibbledata", "gapminder"))
        shell: Rscript {0}
        
      - name: Install colorspace
        run: |
          install.packages("colorspace", repos = "http://R-Forge.R-project.org")
        shell: Rscript {0}

      - name: Install dev cowplot
        run: |
          remotes::install_github("wilkelab/cowplot")
        shell: Rscript {0}

      - name: Install non-CRAN dependencies
        run: |
          remotes::install_github("clauswilke/colorblindr")
        shell: Rscript {0}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: slides/index.qmd